### ISSUE TITLE
bug:不清楚是bug还是哪的问题？

### ISSUE THREAD

**Issue by RiverChu0** [nineya/halo-theme-dream2.0#1]
### 是什么 Halo 版本出现了此问题？

2.4.2

### 使用的 Dream 版本是多少？

1.0.0

### BUG 内容

文章的点赞功能，未登录状态下返回401。登录状态返回404

**Comment by nineya** [comment]
这个功能还没适配，因为没找到halo 2.0的点赞接口

**Comment by forrany** [comment]
> 这个功能还没适配，因为没找到halo 2.0的点赞接口

那是否可以暂时隐藏点赞按钮？

**Comment by nineya** [comment]
可通过定制主题-内嵌css暂时隐藏点赞按钮

**Comment by nineya** [comment]
最新版本已经支持了点赞功能
