### ISSUE TITLE
bug:分类列表排序问题（前台后台显示不一致）

### ISSUE THREAD

**Issue by 457375608** [nineya/halo-theme-dream2.0#107]
### 是什么 Halo 版本出现了此问题？

版本：2.11.3

### 使用的 Dream 版本是多少？

1.3.0

### 在线博客地址

https://blog.liuin.top/

### BUG 内容

![后台](https://github.com/nineya/halo-theme-dream2.0/assets/8923244/1404a8ea-8e58-4883-9ceb-b0f644330c31)
![前台](https://github.com/nineya/halo-theme-dream2.0/assets/8923244/0974fedd-5fd3-4532-a4e3-3878ce9341e3)

期望前台后台显示顺序一致

**Comment by mjsoftking** [comment]
提交给halo了，看看怎么回复的

**Comment by mjsoftking** [comment]
- https://www.sw0.top/docs/halo-theme-dream2.0/release
- 调整了一下下载 1.3.0.6 版本，覆盖安装一下，仅供预览

![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/a17b2318-3b18-4f61-a235-1dce315d0576)

**Comment by 457375608** [comment]
perfect
