### ISSUE TITLE
feat:希望可以像默认主题一样自定义备案号跳转链接

### ISSUE THREAD

**Issue by samyzy** [nineya/halo-theme-dream2.0#114]
### 你当前使用的 Halo 版本

2.12.2

### 你当前使用的 Dream 版本

1.3.0

### 描述一下此特性

如图：
<img width="1089" alt="屏幕截图 2024-02-17 134120" src="https://github.com/nineya/halo-theme-dream2.0/assets/67896769/5a1ee135-e42c-45ec-b0ad-47805f7b65fc">

**Comment by samyzy** [comment]
目前我是通过修改footer.html再重启容器实现，希望后续能够模块化

**Comment by mjsoftking** [comment]
> 目前我是通过修改footer.html再重启容器实现，希望后续能够模块化

当前是不好使吗，还是网站不一样了

**Comment by samyzy** [comment]
> > 目前我是通过修改footer.html再重启容器实现，希望后续能够模块化
> 
> 当前是不好使吗，还是网站不一样了

能用 只是操作比较麻烦 希望能直接集成到设置中

**Comment by mjsoftking** [comment]
https://www.sw0.top/

你看我的站点，这个跳转不存在问题，已经使用最新的域名了，过年那端时间不好使，是公安网站自己的问题
