### ISSUE TITLE
feat:瞬间统计点赞数

### ISSUE THREAD

**Issue by jkjoy** [nineya/halo-theme-dream2.0#116]
### 你当前使用的 Halo 版本

2.12

### 你当前使用的 Dream 版本

1.3

### 描述一下此特性

我发现瞬间点赞之后并没有效果.没有统计点赞数,或者清除本地缓存之后点赞就消失不见,

**Comment by mjsoftking** [comment]
已经修复的，作者未发布，可使用预览版 https://www.sw0.top/docs/halo-theme-dream2.0/release

**Comment by nineya** [comment]
已修复
