### ISSUE TITLE
feat: 适配最新版评论插件

### ISSUE THREAD

**Issue by lis216** [nineya/halo-theme-dream2.0#117]
### 你当前使用的 Halo 版本

2.12.0

### 描述一下此特性

最新版本评论插件在跟主题不适配

**Comment by mjsoftking** [comment]
https://www.sw0.top/docs/halo-theme-dream2.0/release
仅供参考

**Comment by mjsoftking** [comment]
https://www.sw0.top/docs/halo-theme-dream2.0
仅供参考
