### ISSUE TITLE
音乐模块不支持QQ音乐

### ISSUE THREAD

**Issue by ZanJoye** [nineya/halo-theme-dream2.0#125]
### 是什么 Halo 版本出现了此问题？

2.13.1

### 使用的 Dream 版本是多少？

1.3

### 在线博客地址

zanjoye.top

### BUG 内容

使用自建API发现网易的没有问题，但是使用QQ音乐的话，列表图片和歌词都能加载，但是无法播放（报错）

### 附加信息

API: https://api.injahow.cn/meting/

**Comment by nineya** [comment]
非主题适配性问题
