### ISSUE TITLE
custom: 菜单图标

### ISSUE THREAD

**Issue by xJoyLu** [nineya/halo-theme-dream2.0#129]
### 你当前使用的 Dream 版本

1.3.1

### 描述一下此定制化内容

2.0 Dream 在菜单栏没有图标设置项

**Comment by xJoyLu** [comment]
已经在群里获知解决办法。
配置对应 Key
![Uploading WechatIMG6271.jpg…]()

**Comment by xJoyLu** [comment]
done

**Comment by mjsoftking** [comment]
我提交了这个PR，但是没有被合并，优化后是可以直接在元数据中显示相关的配置
