### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by forrany** [nineya/halo-theme-dream2.0#13]
### 是什么 Halo 版本出现了此问题？

 2.5.2

### 使用的 Dream 版本是多少？

1.0.1

### 在线博客地址

http://vincentko.top/message

### BUG 内容

![image](https://github.com/nineya/halo-theme-dream2.0/assets/29779326/e4823740-d9b0-49cf-adc1-da152c85ae47)

暗色主题下，评论的文字看不清楚

**Comment by nineya** [comment]
正常现象，主题无法控制评论区的样式。
可以尝试通过定制主题中内嵌css方式调整背景色以凸显评论区字体
