### ISSUE TITLE
bug: 手机 或小尺寸屏幕 侧边栏 用户信息显示为 已删除用户

### ISSUE THREAD

**Issue by link2fun** [nineya/halo-theme-dream2.0#138]
### 是什么 Halo 版本出现了此问题？

2.15.2

### 使用的 Dream 版本是多少？

1.3.1

### 在线博客地址

https://blog.next2.top

### BUG 内容

手机 或小尺寸屏幕 侧边栏 用户信息显示为 已删除用户
![image](https://github.com/nineya/halo-theme-dream2.0/assets/19241982/03e78439-1945-4d9d-be80-88e46a9ef354)

**Comment by mjsoftking** [comment]
主题设置 - 基础信息 - 作者用户名

**Comment by link2fun** [comment]
> 主题设置 - 基础信息 - 作者用户名

可用, 感谢
