### ISSUE TITLE
feat:期望主题的边侧栏位置，优化一下配置方式

### ISSUE THREAD

**Issue by zyy247796143** [nineya/halo-theme-dream2.0#148]
### 你当前使用的 Halo 版本

1.16.3

### 你当前使用的 Dream 版本

1.3.1

### 描述一下此特性

期望主体的边侧栏配置页面，能调整一下布局。比如像我右边其他主题的截图那样。当不勾选开启的时候，下面的配色框就不显示。勾选了开启，下面的配色才显示。
类似的。像这个主题的，侧边栏信息-开启彩字切换，不开启的时候是否就可以把下面的 侧边栏信息-彩字内容 隐藏起来。开启再显示出来。这样主题布局看起来清爽很多。

![image](https://github.com/nineya/halo-theme-dream2.0/assets/23225911/47d083b4-accc-4a6d-8754-9ff034a30c2c)

**Comment by mjsoftking** [comment]
这种调整会导致已有配置全部失效，基本没法改

**Comment by zyy247796143** [comment]
好吧。不改这样可以。

**Comment by mjsoftking** [comment]
我试过，不用group区分有的时候后台配置就莫名的混乱了，如果用group所有更改的配置都要重新配置一遍
