### ISSUE TITLE
bug: 主题颜色在文章的引用的样式未生效

### ISSUE THREAD

**Issue by forrany** [nineya/halo-theme-dream2.0#16]
### 是什么 Halo 版本出现了此问题？

2.6

### 使用的 Dream 版本是多少？

1.0.2

### 在线博客地址

https://vincentko.top/archives/kosp

### BUG 内容

<img width="1582" alt="image" src="https://github.com/nineya/halo-theme-dream2.0/assets/29779326/ccefaa93-45f9-4c6a-b35c-e985eb8100c9">

如图，主题的颜色使用了自定义的紫色后，其他地方都变了颜色，但是文章页的引用文字的样式，仍然是原来的蓝色，期望能够和主题色一致

**Comment by nineya** [comment]
后面可以考虑对引用和单行代码块使用主题色。
