### ISSUE TITLE
feat:是否可以添加metadata用以判断文章是否显示赞赏按钮

### ISSUE THREAD

**Issue by forrany** [nineya/halo-theme-dream2.0#17]
### 你当前使用的 Halo 版本

2.6

### 你当前使用的 Dream 版本

1.0.2

### 描述一下此特性

<img width="1602" alt="image" src="https://github.com/nineya/halo-theme-dream2.0/assets/29779326/70940aa2-2a7c-4957-9645-f33d988c709d">

目前主题的逻辑是根据是否设置了微信或支付宝的二维码来确定展示“赞赏”按钮。

但这种判断会让博客内的所有文章都会显示该按钮

有一种场景，比如“留言板”页面，就想要一个空的文章，下面是留言内容，不想使其展示“赞赏”按钮； 或者有一些公益类文章，也不想展示“赞赏按钮”

所以是不是可以设置一个metadata来判断?  因为每个文章是可以单独设置metadata的

感谢

**Comment by mjsoftking** [comment]
@forrany  
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/b9471c26-11a0-4aeb-9ea7-76b51ff9a03a)

**Comment by mjsoftking** [comment]
@forrany 
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/209d25de-df89-466d-a895-6307bdb719d0)
