### ISSUE TITLE
bug: 友情链接页面，从导航进入无法加载个人信息

### ISSUE THREAD

**Issue by forrany** [nineya/halo-theme-dream2.0#18]
### 是什么 Halo 版本出现了此问题？

2.6

### 使用的 Dream 版本是多少？

1.0.2

### 在线博客地址

https://vincentko.top

### BUG 内容

<img width="1687" alt="image" src="https://github.com/nineya/halo-theme-dream2.0/assets/29779326/e735d57c-2239-4b0e-a814-87389beb3b6c">
如图，通过导航点进去，信息无法加载

但是刷新页面，可以加载到

**Comment by nineya** [comment]
这个问题已经修复过，下个版本上线，也可拉master的代码。详细见issue#14
