### ISSUE TITLE
feat: 建议移除这种cdn的js，支持自己搭建，或者直接提供按钮关闭相关功能。

### ISSUE THREAD

**Issue by jiangqiang1996** [nineya/halo-theme-dream2.0#19]
### 你当前使用的 Halo 版本

halo2.6.1

### 你当前使用的 Dream 版本

1.0.1

### 描述一下此特性

![%C0L0TN4 YF)K1N6)K ~XC3](https://github.com/nineya/halo-theme-dream2.0/assets/44720422/ef11e477-34eb-4288-aedd-6643521d72c0)

这个加载特别慢，导致整个页面白屏一分多钟，还有一个busuanzi的js文件，完全没响应。

**Comment by nineya** [comment]
关闭补丁模式不会下载该文件
