### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by kongcheng1212** [nineya/halo-theme-dream2.0#21]
### 是什么 Halo 版本出现了此问题？

2.6.0

### 使用的 Dream 版本是多少？

1.02

### 在线博客地址

https://www.douyy.cc

### BUG 内容

跳转友链链接时会出现500报错，切换其他主题能够正常使用！！！   网址：https://www.douyy.cc/about

### 附加信息

![1687790608568](https://github.com/nineya/halo-theme-dream2.0/assets/93602722/40da58e4-785d-4bcf-ab80-926d878eaf98)

**Comment by nineya** [comment]
需要提供后台异常日志才能排查

**Comment by kongcheng1212** [comment]
需要我这边配合呢，后台日志不知道在哪个路径


From: 玖涯
Date: 2023-07-04 14:30
To: nineya/halo-theme-dream2.0
CC: kongcheng1212; Author
Subject: Re: [nineya/halo-theme-dream2.0] bug: (Issue #21)
需要提供后台异常日志才能排查

**Comment by nineya** [comment]
docker挂载出来的路径，翻一翻有个logs目录。

**Comment by kongcheng1212** [comment]
段晓航


手   机：17713607250
***@***.***
 
From: 玖涯
Date: 2023-07-07 11:45
To: nineya/halo-theme-dream2.0
CC: kongcheng1212; Author
Subject: Re: [nineya/halo-theme-dream2.0] bug: (Issue #21)
docker挂载出来的路径，翻一翻有个logs目录。

**Comment by nineya** [comment]
直接回复邮件的内容github上是收不到的
