### ISSUE TITLE
bug:点赞报错

### ISSUE THREAD

**Issue by Alfy-P** [nineya/halo-theme-dream2.0#24]
### 是什么 Halo 版本出现了此问题？

2.6.0

### 使用的 Dream 版本是多少？

1.0.2

### BUG 内容

![image](https://github.com/nineya/halo-theme-dream2.0/assets/84024898/7ae582b3-8b70-43fa-ba1d-12c8894a6712)

**Comment by nineya** [comment]
1.0.3已支持点赞
