### ISSUE TITLE
bug:在该版本中用不了html等特性

### ISSUE THREAD

**Issue by Mr-dadong** [nineya/halo-theme-dream2.0#25]
### 是什么 Halo 版本出现了此问题？

2.7.0

### 使用的 Dream 版本是多少？

1.0.3

### BUG 内容

这段代码实现的效果
在富文本中输入后，在点击预览和发布并没有实现效果。还有其他好多标签也是实现不了效果
![image](https://github.com/nineya/halo-theme-dream2.0/assets/102886401/85d4b251-ff49-476c-ad97-9874720b991c)
![image](https://github.com/nineya/halo-theme-dream2.0/assets/102886401/774819db-3f0c-423a-9294-0de17f1d3cc9)

**Comment by nineya** [comment]
非主题问题，更换编辑器试试

**Comment by Mr-dadong** [comment]
> 非主题问题，更换编辑器试试

三个编辑器全测试了，还是不可以
