### ISSUE TITLE
feat:可否添加一个取消图片文件名显示

### ISSUE THREAD

**Issue by Mr-dadong** [nineya/halo-theme-dream2.0#26]
### 你当前使用的 Halo 版本

2.7.0

### 你当前使用的 Dream 版本

1.0.3

### 描述一下此特性

可否添加一个取消图片文件名显示，有时候不想显示上传文件的文件名，可否添加全局按钮进行关闭或开启

**Comment by nineya** [comment]
可通过自定义css实现，后续版本迭代此功能
