### ISSUE TITLE
feat: 根据图片长宽展示图片

### ISSUE THREAD

**Issue by WaterSunMount** [nineya/halo-theme-dream2.0#28]
### 你当前使用的 Halo 版本

 2.7.0

### 你当前使用的 Dream 版本

 1.0.2

### 描述一下此特性

目前无论如何设置文章图片，都不能达到满意效果
![image](https://github.com/nineya/halo-theme-dream2.0/assets/75781948/c60e1329-b672-4ba1-a643-73d61ba19975)

是否可以根据图片长宽自动适配图片展示
具体思路：找出图片宽或者长最大的尺寸进行等比例缩放，再根据用户配置的展示策略，把图片铺满展示策略的框里面，目前的效果好像是裁剪，就导致了很多图片只能展示部分

这是目前的效果
![image](https://github.com/nineya/halo-theme-dream2.0/assets/75781948/fb509364-9828-46d3-97d3-4e9b9d3a5676)

**Comment by nineya** [comment]
不合适，需要自适应不同屏幕的大小
