### ISSUE TITLE
bug:文章无法显示

### ISSUE THREAD

**Issue by SevenLoveme** [nineya/halo-theme-dream2.0#29]
### 是什么 Halo 版本出现了此问题？

显示错误

### 使用的 Dream 版本是多少？

 1.0.3

### BUG 内容

![image](https://github.com/nineya/halo-theme-dream2.0/assets/69687544/94d6466d-a448-47b5-ade4-7ca60e3ef51d)
显示500但是原始主题正常
![image](https://github.com/nineya/halo-theme-dream2.0/assets/69687544/e4939990-6611-48f8-8236-b8156111ee24)

### 相关 Console 日志输出

```shell
20230707:1 
        
        
        GET http://****.******.com/archives/20230707 500 (Internal Server Error)
jquery.min.js:2 [Violation]Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ jquery.min.js:2
(匿名) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
ke @ jquery.min.js:2
on @ jquery.min.js:2
maskClose @ common.min.js?mew=1.0.3:1
(匿名) @ common.min.js?mew=1.0.3:1
(匿名) @ common.min.js?mew=1.0.3:1
(匿名) @ common.min.js?mew=1.0.3:1
comment-widget.iife.js:19  Element not found #comment
yE @ comment-widget.iife.js:19
initComment @ common.min.js?mew=1.0.3:1
(匿名) @ common.min.js?mew=1.0.3:1
(匿名) @ common.min.js?mew=1.0.3:1
common.min.js?mew=1.0.3:1 页面加载耗时：1540ms | Theme By Dream 1.0.3
halo-tracker.js:1 Visit count:
```

**Comment by nineya** [comment]
需要提供下后台spring.log日志，不然没办法排查

**Comment by SevenLoveme** [comment]
是这个吗 经测试使用Dream1.0.3 出现报错如附件所示




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nineya/halo-theme-dream2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月7日(星期五) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nineya/halo-theme-dream2.0] bug:文章无法显示 (Issue #29)





 
需要提供下后台spring.log日志，不然没办法排查

**Comment by SevenLoveme** [comment]
使用Earth1.4.0 无日志输出 并且前端显示正常



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nineya/halo-theme-dream2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月7日(星期五) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nineya/halo-theme-dream2.0] bug:文章无法显示 (Issue #29)





 
需要提供下后台spring.log日志，不然没办法排查

**Comment by nineya** [comment]
github上收不到附件，可在qq交流群里反馈附件：638168592

**Comment by SevenLoveme** [comment]
已发送申请



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月7日(星期五) 中午11:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nineya/halo-theme-dream2.0] bug:文章无法显示 (Issue #29)





 
github上收不到附件，可在qq交流群里反馈附件：638168592

**Comment by SevenLoveme** [comment]
配置错误 已解决
