### ISSUE TITLE
feat:自动生成摘要不显示

### ISSUE THREAD

**Issue by lcy2002** [nineya/halo-theme-dream2.0#30]
### 你当前使用的 Halo 版本

2.7.0

### 你当前使用的 Dream 版本

1.0.3

### 描述一下此特性

自动生成摘要不显示问题
![1689093606310](https://github.com/nineya/halo-theme-dream2.0/assets/46434481/fc9ae61b-a686-426d-9cb8-cc010fe66a5c)
通过查询Api找出
将${post.spec.excerpt.raw}修改成${post.status.excerpt}就能显示
已验证
![1689093958220](https://github.com/nineya/halo-theme-dream2.0/assets/46434481/991e48dc-024c-477f-93c9-74c5a964f282)

地址：https://spec6.top/

**Comment by nineya** [comment]
感谢，已修复，更新到下个版本上发布

**Comment by space-tk** [comment]
> 
好的 不客气 ^-^

**Comment by space-tk** [comment]
> 感谢，已修复，更新到下个版本上发布

好的 不客气 ^-^
