### ISSUE TITLE
bug:侧边栏标签-开启标签颜色后 文字不显示

### ISSUE THREAD

**Issue by space-tk** [nineya/halo-theme-dream2.0#32]
### 是什么 Halo 版本出现了此问题？

2.7.0

### 使用的 Dream 版本是多少？

1.0.3

### 在线博客地址

https://www.spec6.top/

### BUG 内容

![1689126587790](https://github.com/nineya/halo-theme-dream2.0/assets/88822821/42a16130-f5f3-4415-a3e3-0f1a56a0c199)
侧边栏标签-开启标签颜色后 文字不显示
![1689126603188](https://github.com/nineya/halo-theme-dream2.0/assets/88822821/544669d5-e96a-4b0a-b49d-71a3c9e1243a)
鼠标悬浮后显示
![1689126647068](https://github.com/nineya/halo-theme-dream2.0/assets/88822821/7d3bccb6-fb27-42ef-823b-108f1f8c6960)

**Comment by space-tk** [comment]
> ### 是什么 Halo 版本出现了此问题？
> 2.7.0
> 
> ### 使用的 Dream 版本是多少？
> 1.0.3
> 
> ### 在线博客地址
> https://www.spec6.top/
> 
> ### 错误内容
> ![1689126587790](https://user-images.githubusercontent.com/88822821/252833391-42a16130-f5f3-4415-a3e3-0f1a56a0c199.png)侧边栏标签-开启标签颜色后 文字不显示 鼠标悬浮后显示 ![1689126603188](https://user-images.githubusercontent.com/88822821/252833428-544669d5-e96a-4b0a-b49d-71a3c9e1243a.png) ![1689126647068](https://user-images.githubusercontent.com/88822821/252833435-7d3bccb6-fb27-42ef-823b-108f1f8c6960.png)
> 
> ### 相关 Console 日志输出
> _无响应_
> 
> ### 附加信息
> _无响应_

**Comment by mjsoftking** [comment]
@space-tk 你好，请问如何解决的
