### ISSUE TITLE
https://xxx.com/about/ 与 https://xxx.com/about 显示不是同一个内容

### ISSUE THREAD

**Issue by GuGuGee** [nineya/halo-theme-dream2.0#33]
### 是什么 Halo 版本出现了此问题？

2.7.0

### 使用的 Dream 版本是多少？

1.0.1

### 在线博客地址

https://www.iwanlab.com

### BUG 内容

创建了一个about页面，

https://www.iwanlab.com/about 访问正常

https://www.iwanlab.com/about/   末尾不小心加了`/`之后就会显示404

**Comment by nineya** [comment]
非主题原因，可向halo提issue

**Comment by GuGuGee** [comment]
> 非主题原因，可向halo提issue

好的，谢谢！
