### ISSUE TITLE
feat:能否把2.7.0的搜索框改成1.x版本的那种搜索框

### ISSUE THREAD

**Issue by MrArlong** [nineya/halo-theme-dream2.0#34]
### 你当前使用的 Halo 版本

2.7.0

### 你当前使用的 Dream 版本

1.0.3

### 描述一下此特性

目前2.x是这样的搜索框
![image](https://github.com/nineya/halo-theme-dream2.0/assets/49047855/e9dc5c8e-fba4-4942-8b7e-74a54f999c88)
能否适配成下面这种的
![image](https://github.com/nineya/halo-theme-dream2.0/assets/49047855/cb205214-7fa4-4527-bf07-7d19206e05d3)

**Comment by nineya** [comment]
不行，2.0的搜索框是插件实现的，不受主题控制
