### ISSUE TITLE
feat:文章页左右侧信息展示建议

### ISSUE THREAD

**Issue by RealKiro** [nineya/halo-theme-dream2.0#35]
### 你当前使用的 Halo 版本

2.7

### 你当前使用的 Dream 版本

1.0.3

### 描述一下此特性

浏览某篇文章，左右侧无关信息占比太大，难以把视线焦点放在中间文章上
![image](https://github.com/nineya/halo-theme-dream2.0/assets/33367701/53cb9397-dd25-4136-aaf6-102505592306)

解决思路：
- 左右侧增加展示自定义功能，比如：
1. 左右侧比例缩小，中心聚焦
2. 左侧或右侧添加目录展示，方便随时跳转阅读

**Comment by nineya** [comment]
主题不考虑调整比例，可通过自定义css内容修改比例，或者改为双列布局。
