### ISSUE TITLE
feat:亮色主题下tag标签看不清的临时解决办法

### ISSUE THREAD

**Issue by 873485077** [nineya/halo-theme-dream2.0#36]
### 你当前使用的 Halo 版本

2.7

### 你当前使用的 Dream 版本

1.0.4

### 描述一下此特性

原问题请查看
https://github.com/nineya/halo-theme-dream/issues/152#issuecomment-1647690849

**Comment by nineya** [comment]
halo中未配置标签色

**Comment by Mrered** [comment]
> halo中未配置标签色

我懂了，知道如何解决了，但是默认创建的新标签颜色都是白色的，这咋办
