### ISSUE TITLE
bug: themes/theme-dream/assets/js/journals.min.js?mew=1.0.4 404

### ISSUE THREAD

**Issue by hlovingness** [nineya/halo-theme-dream2.0#37]
### 是什么 Halo 版本出现了此问题？

2.7

### 使用的 Dream 版本是多少？

 1.0.4

### BUG 内容

themes/theme-dream/assets/js/journals.min.js?mew=1.0.4 net::ERR_ABORTED 404

**Comment by nineya** [comment]
尝试更新一下主题试试
