### ISSUE TITLE
bug: 标签颜色是白色的，看不见了

### ISSUE THREAD

**Issue by hlovingness** [nineya/halo-theme-dream2.0#38]
### 是什么 Halo 版本出现了此问题？

2.7

### 使用的 Dream 版本是多少？

 1.0.4

### 在线博客地址

https://adger.me

### BUG 内容

![image](https://github.com/nineya/halo-theme-dream2.0/assets/16331459/25384958-138d-4954-9fd6-3f3b08736baf)

**Comment by nineya** [comment]
没有配置标签色，也可以关闭标签颜色功能
