### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by OldMonster1** [nineya/halo-theme-dream2.0#39]
### 是什么 Halo 版本出现了此问题？

2.7

### 使用的 Dream 版本是多少？

 1.0.4

### 在线博客地址

https://ffbf.top/

### BUG 内容

1.页面跳转设置了本页跳转也会强制新窗口跳转
2.评论不可用
3.二级分类和一级分类同行显示了
4.希望大佬早点适配相册、弹幕、自定义图标那些功能

**Comment by OldMonster1** [comment]
信息模块的“评论”能换回老版本的“标签”吗

**Comment by nineya** [comment]
1、2两项问题已修复，下个版本发布
3无法支持、弹幕无法支持、信息模块的“评论”无法切换回老版本的“标签”
相册看后面插件是否能有功能优化，目前没计划适配
