### ISSUE TITLE
bug:关闭文章设置里的版权声明查看文章报500错误

### ISSUE THREAD

**Issue by yidit** [nineya/halo-theme-dream2.0#4]
### 是什么 Halo 版本出现了此问题？

2.5.2

### 使用的 Dream 版本是多少？

1.0.1

### BUG 内容

关闭文章设置里的版权声明查看文章报500错误
异常信息：
Internal Server Error:
Something went wrong, please try again later.

**Comment by nineya** [comment]
该问题已修复，下个版本正式发布上
