### ISSUE TITLE
bug:音乐模块播放音乐，然后点击其它文章或菜单音乐就没了

### ISSUE THREAD

**Issue by dengchuanfu** [nineya/halo-theme-dream2.0#41]
### 是什么 Halo 版本出现了此问题？

 1.0.5

### 使用的 Dream 版本是多少？

 2.7.0

### 在线博客地址

https://ffbf.top/

### BUG 内容

音乐模块播放音乐，然后点击其它文章或菜单音乐就没了，整个页面被刷新

**Comment by dengchuanfu** [comment]
瞬间插件不支持评论，插件那边说评论组件是主题这边决定的，向对应主题的作者反馈下。

**Comment by nineya** [comment]
没有开启pajx，音乐中断是正常现象

**Comment by nineya** [comment]
> 瞬间插件不支持评论，插件那边说评论组件是主题这边决定的，向对应主题的作者反馈下。

瞬间评论主题提供了配置可以开启评论，但是不建议使用该功能。瞬间的评论和点赞都有缺陷，无法正确显示计数，后续如果有修复方法进行修复时可能评论会丢失。

**Comment by OldMonster1** [comment]
开启pajx正常了，瞬间再等等吧
