### ISSUE TITLE
bug: 亮主题下苹果手机使用微信自带的浏览器不显示留言边框

### ISSUE THREAD

**Issue by WaterSunMount** [nineya/halo-theme-dream2.0#42]
### 是什么 Halo 版本出现了此问题？

2.8.0

### 使用的 Dream 版本是多少？

 1.0.4

### BUG 内容

![b6700369d61ed5beb40df29c842a86d](https://github.com/nineya/halo-theme-dream2.0/assets/75781948/5453852d-7926-4d5a-9cad-33e363a93948)
手机端评论组件，没有边框
而且评论中昵称和邮箱选项能不能加个必填的星号，好几个人问我这个不能登录了

**Comment by WaterSunMount** [comment]
安卓手机上就算白色背景下也有，苹果手机白色背景下就没有边框
https://blog-trick.peakliu.top/archives/1692333907684

**Comment by nineya** [comment]
这不是主题的问题，大概率是留言插件的问题
