### ISSUE TITLE
feat:能否修改一下代码块中的代码样式

### ISSUE THREAD

**Issue by Sakura-LF** [nineya/halo-theme-dream2.0#43]
### 你当前使用的 Halo 版本

2.8

### 你当前使用的 Dream 版本

最新版

### 描述一下此特性

就是主题里面的代码块看着有点儿难受 , 我觉得应该把字体加粗一些或者换个字体 , 图2是hao主题中的代码块 , 图三是 IDE 里的 , 用的字体是 Cascadia Code

另外就是编辑页面的代码格式和发布后的代码格式不一致 , 发布后的缩进了8个空格 , 这是直接从IDE复制过去的代码 , 直接在编辑页面写的话没有格式问题 , 不知道是halo富文本编辑器的问题还是主题的问题

![image](https://github.com/nineya/halo-theme-dream2.0/assets/80140609/37f90fad-c200-4990-9cf6-cb05ca5d2b4c)
![image](https://github.com/nineya/halo-theme-dream2.0/assets/80140609/8ed5b7bc-ee14-4b1d-9c1f-6b61c271e78c)
![image](https://github.com/nineya/halo-theme-dream2.0/assets/80140609/d94b0cec-14fc-45e6-8178-6802535327a8)

**Comment by nineya** [comment]
字体后续可以调整，缩进问题理论上不是主题的问题，换个主题后缩进就正常了吗？如果是的话需要提供一下问题文章的博客地址
