### ISSUE TITLE
feat: dream主题中文章的table表格支持自动调整宽度

### ISSUE THREAD

**Issue by zyy247796143** [nineya/halo-theme-dream2.0#45]
### 你当前使用的 Halo 版本

2.9

### 你当前使用的 Dream 版本

1.0.5

### 描述一下此特性

目前dream主题的表格，视乎不会调整表格的宽度，导致有时会看起来不太舒服。比如这样，红框中的区域空白地方过多：
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23225911/ec4839d0-4f74-44d1-a165-8c6295f504a3)

希望可以支持默认调整格子的宽度，看起来好看一些，表格更紧凑，比如这样：
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23225911/73acedb8-fd85-4de7-8208-cb52be3d34d1)

**Comment by nineya** [comment]
下个版本优化
