### ISSUE TITLE
bug:文章版权声明链接显示错误

### ISSUE THREAD

**Issue by swRains** [nineya/halo-theme-dream2.0#46]
### 是什么 Halo 版本出现了此问题？

最新版

### 使用的 Dream 版本是多少？

1.0.5

### BUG 内容

BUG 内容
1、[ 开启文章版权声明  如果文章或页面元数据配置了enable_copyright项，则当前配置将被覆盖。]
开启该项目后文章下版权声明的下方显示的本文链接是localhost:8090，虽然点击跳转正常但是显示是错误的、

2、网页左上角和左下角的网页名称的链接地址也是localhost：8090

搭建流程：docker搭建halo，nginx反代8090端口并添加ssl

### 附加信息

<img width="495" alt="屏幕截图 2023-09-15 012544" src="https://github.com/nineya/halo-theme-dream2.0/assets/96161478/64857b06-391e-40eb-a77c-4c78ce0ac048">

**Comment by swRains** [comment]
找到了，是我设置问题，打扰了

**Comment by lingdiansr** [comment]
您好，我使用1panel安装halo，使用主题Theme Joe3，能否借鉴一下您是怎么解决这个问题的？
