### ISSUE TITLE
feat:显示问题安全性问题

### ISSUE THREAD

**Issue by alawn-wang** [nineya/halo-theme-dream2.0#47]
### 你当前使用的 Dream 版本

 1.1.0

### 描述一下此特性

处于安全性考虑，对于文章或者页面展示时，暴露端口或者用户权限并不是一个很好的选择，不知道该主题是否可以展示页面链接时展示为http://domin/links。而在展示作者时用户名替代权限可能更好？也可能是因为我没有新建其他用户，仅用了administrator用户，但该用户的用户名并不为administrator

### 附加信息

<img width="560" alt="1695456213808" src="https://github.com/nineya/halo-theme-dream2.0/assets/64401632/780f734b-81e9-4244-adaf-6cc1e73ba820">

**Comment by nineya** [comment]
本身展示的就是用户名

**Comment by alawn-wang** [comment]
ok，关于用户名已经测试出来了，展示的应该是“显示名称”，而非“用户名”，如下。同时想请问下有计划将ip:port的展示切换为domain吗？
![1695805612907](https://github.com/nineya/halo-theme-dream2.0/assets/64401632/2669ec77-5c5f-450d-aa7c-c081bc1f4f42)

**Comment by nineya** [comment]
这些问题与主题无关，检查一下halo的配置，或者更换几个主题看看是否也存在一样的问题
