### ISSUE TITLE
feat:相册页是否可以设置缩略图参数？

### ISSUE THREAD

**Issue by zyy247796143** [nineya/halo-theme-dream2.0#48]
### 你当前使用的 Halo 版本

2.9.2

### 你当前使用的 Dream 版本

1.1.0

### 描述一下此特性

相册页在不点开照片的时候是否可以只加载缩略图？或者可以自定义缩略图参数？目前相册页里有很多照片的时候，都是直接下载原图的。比如我的网站，一点开相册页第一页全部加载完成的时候，已经消耗了60多M的网络流量。可以设置缩略图就可以更快打开页面，也可以节省流量。

**Comment by nineya** [comment]
不能，在halo给的参数中没找到缩略图的参数
