### ISSUE TITLE
bug:侧边栏配置-开启标签颜色显示异常

### ISSUE THREAD

**Issue by fanfanxhf** [nineya/halo-theme-dream2.0#5]
### 是什么 Halo 版本出现了此问题？

 2.5.1

### 使用的 Dream 版本是多少？

1.0.1

### BUG 内容

侧边栏配置-开启标签颜色
标签全是白色,导致看上去什么都没有
![image](https://user-images.githubusercontent.com/28796841/236613168-ee3da1ae-3806-4d13-b50f-98668c7bf5d1.png)
![image](https://user-images.githubusercontent.com/28796841/236613203-fe33522b-2c36-4d7d-8217-c565ecd5e8f1.png)

**Comment by nineya** [comment]
你没指定标签色，halo默认给了白色

**Comment by fanfanxhf** [comment]
ok,我看看

**Comment by fanfanxhf** [comment]
> 你没指定标签色，halo默认给了白色
可以了,谢谢

**Comment by fanfanxhf** [comment]
@
