### ISSUE TITLE
bug:翻页数据不对

### ISSUE THREAD

**Issue by yankooo** [nineya/halo-theme-dream2.0#51]
### 是什么 Halo 版本出现了此问题？

2.8.0

### 使用的 Dream 版本是多少？

1.1.1

### BUG 内容

<img width="997" alt="image" src="https://github.com/nineya/halo-theme-dream2.0/assets/31951382/1416a7e9-e834-4ee8-bb6e-1b8f4b7b9359">
比如这样，翻到第五页，实际上应该展示到下一个5页，但是没变化，看不出来后面还有页

**Comment by nineya** [comment]
选中第五页时会展示3,4,【5】,6,7

**Comment by yankooo** [comment]
没有，我点到第五页都没变化，需要点旁边的 「下一页」 才会翻页
<img width="1032" alt="image" src="https://github.com/nineya/halo-theme-dream2.0/assets/31951382/2540e573-534f-498c-9377-dd681d24574c">

**Comment by nineya** [comment]
方便的话可以提供下博客地址

**Comment by yankooo** [comment]
https://ppxai.com/index/page/5

主题换好了，大佬去看吧，必现，我用的是最新版本halo和主题

**Comment by nineya** [comment]
该问题已修复，在下个版本上更新
