### ISSUE TITLE
bug:公网安备的logo不行了

### ISSUE THREAD

**Issue by wpengsen** [nineya/halo-theme-dream2.0#54]
### 是什么 Halo 版本出现了此问题？

2.10

### 使用的 Dream 版本是多少？

2.0

### 在线博客地址

https://bangkaixin.com

### BUG 内容

公网安备的logo网址估计换了https://beian.mps.gov.cn/web/assets/logo01.6189a29f.png

**Comment by mjsoftking** [comment]
这种小图标不占用太多流量，可以弄成静态资源去访问。

交互式网站申请麻烦不。

**Comment by theLastWinner** [comment]
@nineya 请问一下，这个有打算什么时候升级解决吗？目前看博客，那个地方会比较突兀。谢谢。

**Comment by mjsoftking** [comment]
@theLastWinner 
如果急于使用参考
[Halo博客 - 主题Dream for Halo 2.x 测试版](https://www.sw0.top/archives/nhi5LoK2)
按引导操作。

**Comment by theLastWinner** [comment]
> @theLastWinner 如果急于使用参考 [Halo博客 - 主题Dream for Halo 2.x 测试版](https://www.sw0.top/archives/nhi5LoK2) 按引导操作。

@mjsoftking 好的，谢谢。
