### ISSUE TITLE
custom:

### ISSUE THREAD

**Issue by mjsoftking** [nineya/halo-theme-dream2.0#56]
### 你当前使用的 Dream 版本

1.1.1

### 描述一下此定制化内容

halo版本2.10.2
当前主题的侧边栏-信息模块，可否自定义配置显示哪几项或者如何操作可以不显示 评论选项

**Comment by nineya** [comment]
不能自定义配置

**Comment by mjsoftking** [comment]
@nineya 感谢大佬付出，另外可否告知一下这里有没有表示标签数量的字段呀
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/5237edd6-3a0c-410f-bc25-498359fc53a3)

**Comment by nineya** [comment]
没有，就是因为没有才用评论替代

**Comment by mjsoftking** [comment]
好吧，感谢，非交互式备案，看到不太好，●﹏●
