### ISSUE TITLE
bug:Pjax 加载开启时能否使阅读限制插件失效

### ISSUE THREAD

**Issue by mjsoftking** [nineya/halo-theme-dream2.0#57]
### 是什么 Halo 版本出现了此问题？

2.10.2

### 使用的 Dream 版本是多少？

1.1.1

### BUG 内容

百度一下怀疑是Pjax的装载容器未加载js导致，不太懂前端的东西。
大佬有时间可以看看，处理不了的话就不用了。
[https://www.javazxz.com/thread-3765-1-1.html](https://www.javazxz.com/thread-3765-1-1.html)
网上找的一种情况处理，不知道适不适用。

![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/c92e8e3e-18f1-42b0-9855-535ff9a7c567)
开启后第二次打开页面，隐藏内容无法查看了
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/ebd46d72-8d17-486c-a8f4-fe65ed2d5f3e)

**Comment by nineya** [comment]
pjax可能导致插件问题，建议关闭pjax
