### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by hcejlo55** [nineya/halo-theme-dream2.0#7]
### 是什么 Halo 版本出现了此问题？

2.5.2

### 使用的 Dream 版本是多少？

1.0.1

### 在线博客地址

https://www.mzchn.cn/links

### BUG 内容

友情链接界面显示null的小伙伴们

### 相关 Console 日志输出

```shell
页面加载耗时：3156ms | Theme By Dream 1.0.1
VM66:738  Element not found #comment
b8 @ VM66:738
```

### 附加信息

![image](https://github.com/nineya/halo-theme-dream2.0/assets/128951503/f463ab85-c645-43ee-b443-ff629b62731b)

**Comment by nineya** [comment]
用户名配置错误？
