### ISSUE TITLE
feat: 关于友链支持配置关于站点信息还是关于用户信息展示友链内容

### ISSUE THREAD

**Issue by mjsoftking** [nineya/halo-theme-dream2.0#73]
### 你当前使用的 Dream 版本

1.1.1

### 描述一下此定制化内容

**默认为关联用户与原设计一致**

- 主题设置

![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/6afb5a64-0173-404b-a46f-df28201ab7db)

- 关联用户

![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/7b77aecb-92e3-4265-9532-374118bf0c2f)

- 关联站点

![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/c21a6f7f-5a9c-4a3d-a5a8-c8f8c670cd78)

**Comment by mjsoftking** [comment]
@nineya 避免无意义的提交PR，这样修改是否可以接受呢

**Comment by nineya** [comment]
不考虑新增配置项
