### ISSUE TITLE
bug: 1.2.0 打开评论模块会出现 500服务器内部错误

### ISSUE THREAD

**Issue by forrany** [nineya/halo-theme-dream2.0#75]
### 是什么 Halo 版本出现了此问题？

2.11

### 使用的 Dream 版本是多少？

1.2.0

### 在线博客地址

https://vincentko.top

### BUG 内容

<img width="1923" alt="image" src="https://github.com/nineya/halo-theme-dream2.0/assets/29779326/495351aa-1396-4402-8f35-ac5d862df6a5">

<img width="2547" alt="image" src="https://github.com/nineya/halo-theme-dream2.0/assets/29779326/1e68b286-3e86-4915-bac4-2e68677a2b83">

发现只要打开了评论模块，就会出现这个问题，关闭则ok

看了评论列表，也没有 ‘有问题的’ 评论，如下图：
<img width="2295" alt="image" src="https://github.com/nineya/halo-theme-dream2.0/assets/29779326/2e95a892-b0e8-462b-866c-af1c42770304">

**Comment by nineya** [comment]
看不出问题，需要导出后台日志才行
