### ISSUE TITLE
custom:导航栏图标配置方式

### ISSUE THREAD

**Issue by lis216** [nineya/halo-theme-dream2.0#78]
### 你当前使用的 Halo 版本

2.11.3

### 你当前使用的 Dream 版本

1.2.1

### 描述一下此特性

可配置导航栏图标

**Comment by mjsoftking** [comment]
是说的halo后台菜单设置吗

![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/857e225b-be86-4862-8f4f-6abb00f2e4d0)
手动添加元数据 icon，值填：remix的图标，好像是3.5版本的

**Comment by lis216** [comment]
> remix

好的  感谢

**Comment by nineya** [comment]
remix版本：3.5.0
官网：https://remixicon.com/
