### ISSUE TITLE
feat:建议如果没有启用的功能不加载其js。

### ISSUE THREAD

**Issue by lis216** [nineya/halo-theme-dream2.0#81]
### 你当前使用的 Halo 版本

2.11.3

### 你当前使用的 Dream 版本

1.2.1

### 描述一下此特性

比如busuanzi，加载有的时候非常慢，关闭之后js还是会加载

**Comment by mjsoftking** [comment]
https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

直接访问倒是没有那么慢，我今天也是不加载具体统计结果，估计是网站维护了吧

**Comment by lis216** [comment]
> https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
> 
> 直接访问倒是没有那么慢，我今天也是不加载具体统计结果，估计是网站维护了吧

所以建议如果后台配置不启用就不加载该js。

**Comment by mjsoftking** [comment]
这个平台不是502就是504的

**Comment by mjsoftking** [comment]
我估计作者原设计应该是关闭只是不显示不意味着不进行统计，否则关闭的时候就会丢失统计数据了

**Comment by lis216** [comment]
> 这个平台不是502就是504的
> 
> 另外关于 #80 能正确填写吗。

这个没试过欸。

**Comment by lis216** [comment]
> 我估计作者原设计应该是关闭只是不显示不意味着不进行统计，否则关闭的时候就会丢失统计数据了

这个可以在原来基础上加个开关  不加载资源文件。而且不知道halo2的模板是怎么加载的 我直接改template下的模板文件  前端并没有生效

**Comment by mjsoftking** [comment]
我也试了一下没生效，不知道是否和那个异步加载有关

**Comment by lis216** [comment]
> 我也试了一下没生效，不知道是否和那个异步加载有关

哪个异步加载。还有就是首页展示评论模块。头像也不展示

**Comment by mjsoftking** [comment]
> 还有就是首页展示评论模块。头像也不展示

单独开一个issue提交评论模块问题，最好截图说明。

**Comment by mjsoftking** [comment]
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/e29e3bc9-ea75-4e37-84f7-900f72a26b2d)
用的th:if判断的，没生效，也可能是配置参数没用对

**Comment by lis216** [comment]
> ![image](https://private-user-images.githubusercontent.com/23021469/293658215-e29e3bc9-ea75-4e37-84f7-900f72a26b2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODgwMzcsIm5iZiI6MTcwNDE4NzczNywicGF0aCI6Ii8yMzAyMTQ2OS8yOTM2NTgyMTUtZTI5ZTNiYzktZWE3NS00ZTM3LTg0ZjctOTAwZjcyYTI2YjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA5Mjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YTM5M2ZkYjg3ZTJmZjAyZGZkMzExYzBlYzBhNGVhZDVlMGYxODYzOTJkOWViMTY0YzMzNTAwODM3N2E2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FxV0I-TZcyX2jKc05BRDEBZcazYVeoByEYsesDNPcCs) 用的th:if判断的，没生效，也可能是配置参数没用对

没用的  我把这行注释掉都不行

**Comment by nineya** [comment]
该功能已实现，下个版本带上
