### ISSUE TITLE
bug:首页的最新评论模块没有头像展示

### ISSUE THREAD

**Issue by lis216** [nineya/halo-theme-dream2.0#82]
### 是什么 Halo 版本出现了此问题？

2.11.3

### 使用的 Dream 版本是多少？

1.2.1

### BUG 内容

![屏幕截图 2024-01-02 173140](https://github.com/nineya/halo-theme-dream2.0/assets/24983401/b713fd01-d3f0-407c-8bae-563b4240274a)
这是文章里的评论
![屏幕截图 2024-01-02 173318](https://github.com/nineya/halo-theme-dream2.0/assets/24983401/aa766dbc-c355-4e83-b4d6-08ac64b296d6)
但是文章里的评论字体好像不对

**Comment by mjsoftking** [comment]
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/86c12ae5-92fd-4489-9e75-a3b66dcd93d8)
看了下返回对象定义，字段没问题，估计返回空了
文章的评论是来源评论组件的，侧边栏是主题的，主题字体样式估计是没能影响到组件

**Comment by lis216** [comment]
> ![image](https://private-user-images.githubusercontent.com/23021469/293666555-86c12ae5-92fd-4489-9e75-a3b66dcd93d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTU3MzgsIm5iZiI6MTcwNDE5NTQzOCwicGF0aCI6Ii8yMzAyMTQ2OS8yOTM2NjY1NTUtODZjMTJhZTUtOTJmZC00NDg5LTllNzUtYTNiNjZkY2Q5M2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDExMzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YmU2OWUyMzZmZjZmZWM0ZmVlZTY0OTM1ZDUxNzBmYzhmODY2Y2MwYzYyOTMyMjlhMGIwMDA4MmQxMGE2MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3pnEIO9P4QoT6VMC3b3dilQpJFMS8bCWflmZExGLVjI) 看了下返回对象定义，字段没问题，估计返回空了 文章的评论是来源评论组件的，侧边栏是主题的，主题字体样式估计是没能影响到组件

应该是有点小bug

**Comment by mjsoftking** [comment]
看了下评论组件里关于账号和无账号评论，应该是2个div干的，有头像就显示<img>无头像就<div>加<span>
这需要样式调整，我不擅长，你有兴趣可以尝试修改下，提交PR。
修改此文件：`halo-theme-dream2.0/templates/widget/recent_comments.html`

**Comment by mjsoftking** [comment]
@lis216 
不会搞样式
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/8640dc46-c30c-4c35-8063-4722c49a7e11)
 始终对不齐

**Comment by mjsoftking** [comment]
现学现做了

**Comment by lis216** [comment]
> 现学现做了

666呀  可以的

**Comment by mjsoftking** [comment]
> > 现学现做了
> 
> 666呀 可以的

关于字体那个我是没办法了，可以独立提issue并@作者，能改的话，作者有时间应该会改

**Comment by mjsoftking** [comment]
不知道作者干啥去了，发布了一个体验版 https://www.sw0.top/docs/halo-theme-dream2.0/release
