### ISSUE TITLE
feat: 主题设置里` 侧边栏信息-统计 `里，也能能带动移动版页面的统计信息

### ISSUE THREAD

**Issue by zyy247796143** [nineya/halo-theme-dream2.0#85]
### 描述一下此特性

希望主题设置里` 侧边栏信息-统计 `里，也能能带动移动版页面的统计信息。
现在移动版页面的统计信息只能固定式文章、分类、评论，不能跟随桌面版页面的信息统计设置。比如这个位置：
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23225911/200555de-5356-4f01-9edf-564fee335a64)

**Comment by mjsoftking** [comment]
![42d919aacb0d5052c1b47ce64f9b2c3](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/64c03516-d120-463a-a586-fe1dabcab8c3)
`侧边栏信息-统计` 控制的是这里的
你那个是哪个模块的

**Comment by mjsoftking** [comment]
找到了，再菜单里

**Comment by zyy247796143** [comment]
小屏界面的左上角菜单里

**Comment by mjsoftking** [comment]
@zyy247796143 
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/2cf8e7ec-aca4-4477-9602-eb33778d2912)
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/9de4e228-faa8-4d4e-b4ec-c2ca0931d6ab)

**Comment by zyy247796143** [comment]
是的，是这里

**Comment by mjsoftking** [comment]
> 是的，是这里

调整了，等当前PR合并后在提交PR
