### ISSUE TITLE
bug:文章中的评论字体样式 与主题设置的不一致

### ISSUE THREAD

**Issue by lis216** [nineya/halo-theme-dream2.0#87]
### 是什么 Halo 版本出现了此问题？

2.11.3

### 使用的 Dream 版本是多少？

1.2.1

### BUG 内容

文章中的评论字体样式 与主题设置的不一致

**Comment by lis216** [comment]
@nineya

**Comment by nineya** [comment]
评论去是插件，不受主题控制

**Comment by mjsoftking** [comment]
@lis216 搜索和评论最新版本插件已经提供支持，现可以跟随主题设置了

https://www.sw0.top/docs/halo-theme-dream2.0
仅供参考
