### ISSUE TITLE
custom:为导航栏添加图标icon

### ISSUE THREAD

**Issue by colordi** [nineya/halo-theme-dream2.0#92]
### 你当前使用的 Dream 版本

1.2.1

### 描述一下此定制化内容

目前根据您的教程里导航栏的配置图标，在2.x的halo里找不到菜单栏设置的【图标】这个元数据，应该是2.0相比于1.0去掉了，请问在2.0中是否可以通过自定义元数据的形式添加回来还是无法实现？

**Comment by nineya** [comment]
2.0通过元数据 icon 配置，看 #78

**Comment by colordi** [comment]
收到，感谢大佬！！！
