### ISSUE TITLE
bug: 文章页中表格的右边框空白较多

### ISSUE THREAD

**Issue by zyy247796143** [nineya/halo-theme-dream2.0#94]
### 是什么 Halo 版本出现了此问题？

2.11.3

### 使用的 Dream 版本是多少？

1.2.1

### BUG 内容

文章页中的表格宽度显示有问题，右边框不会跟着表格的宽度走。如图所示：

![image](https://github.com/nineya/halo-theme-dream2.0/assets/23225911/aec59ef9-c917-4d08-ae71-0ab3fb3bdc73)

**Comment by mjsoftking** [comment]
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/4b71c526-5c6f-455f-abe7-55c8c929e021)
不知道官方这个修复好不好使

**Comment by zyy247796143** [comment]
> ![image](https://private-user-images.githubusercontent.com/23021469/298237439-4b71c526-5c6f-455f-abe7-55c8c929e021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MDgwNzMsIm5iZiI6MTcwNTgwNzc3MywicGF0aCI6Ii8yMzAyMTQ2OS8yOTgyMzc0MzktNGI3MWM1MjYtNWM2Zi00NTVmLWFiZTctNTVjOGM5MjllMDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAzMjkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNGE2ZDgwNzRlZjc2Zjg1MDg0ZTA0MGJlNmNhNzM2ZjU4NDQzYTY5ZDkxYjMyNTU1Mzg1NjJhMDZmMDQ5ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cv9Aewn8nKpwyM88uubw24Gu-N65Wj1T8EhEaQHu6lE) 不知道官方这个修复好不好使

---
刚更新了，不幸没修复到……

**Comment by mjsoftking** [comment]
> > ![image](https://private-user-images.githubusercontent.com/23021469/298237439-4b71c526-5c6f-455f-abe7-55c8c929e021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MDgwNzMsIm5iZiI6MTcwNTgwNzc3MywicGF0aCI6Ii8yMzAyMTQ2OS8yOTgyMzc0MzktNGI3MWM1MjYtNWM2Zi00NTVmLWFiZTctNTVjOGM5MjllMDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAzMjkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNGE2ZDgwNzRlZjc2Zjg1MDg0ZTA0MGJlNmNhNzM2ZjU4NDQzYTY5ZDkxYjMyNTU1Mzg1NjJhMDZmMDQ5ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cv9Aewn8nKpwyM88uubw24Gu-N65Wj1T8EhEaQHu6lE) 不知道官方这个修复好不好使
> 
> 刚更新了，不幸没修复到……

可以考虑去halo提issues，估计是官方渲染的问题

**Comment by zyy247796143** [comment]
我刚用halo默认的Earth主题试了一下，显示没问题喔
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23225911/88801463-03b3-4f68-b460-a18ae72e62e2)

**Comment by mjsoftking** [comment]
> 我刚用halo默认的Earth主题试了一下，显示没问题喔 ![image](https://private-user-images.githubusercontent.com/23225911/299864330-88801463-03b3-4f68-b460-a18ae72e62e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTU4NDEsIm5iZiI6MTcwOTA5NTU0MSwicGF0aCI6Ii8yMzIyNTkxMS8yOTk4NjQzMzAtODg4MDE0NjMtMDNiMy00ZjY4LWI0NjAtYTE4YWU3MmU2MmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA0NDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNDBhNmI3MTdlYWUwMjk1ZTk3ZjU5NzU2ZjFkYTAzMmI0N2IxNWMyN2IzOGM2ODY4MGFmOTRmYmQ2NDAyYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kW-I6mYIWyUduVVPtLz-5b4DQIry5btr-2xOSFiTTtU)

更新到2.12后重新编辑一次文章就有这个宽度属性了，另外调整了部分样式，可以看看 https://www.sw0.top/docs/halo-theme-dream2.0
