### ISSUE TITLE
feat: 适配朋友圈插件

### ISSUE THREAD

**Issue by mjsoftking** [nineya/halo-theme-dream2.0#96]
### 描述一下此定制化内容

feat: 适配朋友圈插件

**Comment by mjsoftking** [comment]
@nineya 可以考虑升级个版本了

**Comment by mjsoftking** [comment]
由于涉及大量css，未在主站发布，预览参考[主题调试站](https://blog.ssrpro.top:8999/friends)

**Comment by mjsoftking** [comment]
@nineya 
- 优化相册界面标题和浏览器标签页标题跟随相册插件的页面标题设置 
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/747f80ae-5144-48f5-8299-00be4168d041)
- 优化瞬间界面标题和浏览器标签页标题跟随瞬间插件的页面标题设置
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/d3f56c1e-1fa0-4c50-9b7f-5af26d9abae6)

这2个修改也提交下

**Comment by nineya** [comment]
瞬间没有选项内容，不带标签
朋友圈样式问题较多，后续再调整

**Comment by nineya** [comment]
![image](https://github.com/nineya/halo-theme-dream2.0/assets/58282918/0e124921-adff-4271-8e41-38c6f5fb0ca4)

**Comment by mjsoftking** [comment]
没用过这么多字的，限制内容字数

**Comment by mjsoftking** [comment]
瞬间没有选项内容，不带标签

感觉有点突兀，所以加了一下

**Comment by mjsoftking** [comment]
> ![image](https://private-user-images.githubusercontent.com/58282918/298444583-0e124921-adff-4271-8e41-38c6f5fb0ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTM4MTksIm5iZiI6MTcwNTg5MzUxOSwicGF0aCI6Ii81ODI4MjkxOC8yOTg0NDQ1ODMtMGUxMjQ5MjEtYWRmZi00MjcxLThlNDEtMzhjNmY1ZmIwY2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAzMTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NjIwNzUwZjJlYjM2MDgwZDM5ZGMyZGNmNjgxZjhhNThhMjE4ZjMyYzYxOTVjN2U1ZDM0MTJmMzVkZDNmNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kTdcKIy-O9dw-6OPM-YgfnXtqHBvoILYygctyCryZf4)

什么浏览器的
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/9e2a6c88-c44f-4739-ac02-dfcae9ac5de0)
本身有字数限制

**Comment by mjsoftking** [comment]
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/56d575e1-39f1-40c2-a0a5-cbfde779ba59)

**Comment by mjsoftking** [comment]
@nineya 限制了150字
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/aec4e821-7085-47ab-9383-1deafaf8cb1d)

**Comment by mjsoftking** [comment]
@nineya 
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/23795422-482c-47c8-b659-e3deeee15f53)
这个图标还是强制限制一下宽高为好
