### ISSUE TITLE
bug:版权声明，网址的域名后出现了2个/，但能正常跳转

### ISSUE THREAD

**Issue by mengtaixiao** [nineya/halo-theme-dream2.0#98]
### 是什么 Halo 版本出现了此问题？

 2.11.3

### 使用的 Dream 版本是多少？

1.2.1

### 在线博客地址

https://blog.209902.xyz/archives/1705574168512

### BUG 内容

![image](https://github.com/nineya/halo-theme-dream2.0/assets/43106255/02d617f0-935d-4879-99c5-1a8682cd3075)
![image](https://github.com/nineya/halo-theme-dream2.0/assets/43106255/485793f8-1158-4c79-80d0-239ba9326f21)
![image](https://github.com/nineya/halo-theme-dream2.0/assets/43106255/b876092f-3e94-4998-a638-f5b1421f42f7)

**Comment by mengtaixiao** [comment]
是docker-compose里面，外部地址后面不用写/吗，我看halo官方的文档里面是加上了的
我试过不带/，好像登不上后台

https://docs.halo.run/getting-started/install/docker-compose
![image](https://github.com/nineya/halo-theme-dream2.0/assets/43106255/e3d35f0f-6fcd-47e6-a3eb-1fcfbb383474)

**Comment by mjsoftking** [comment]
不带也可以的，我的网站就没带，只是之前微信同步插件要求携带/

**Comment by mjsoftking** [comment]
'--halo.external-url=https://www.sw0.top'

**Comment by mengtaixiao** [comment]
> '--halo.external-url=[https：//www.sw0.top](https://www.sw0.top)'刚刚尝试了一下微信同步好吗？

可以了，docker-compose里halo.external-url末尾不带/，正常显示了。
之前可能是更新docker-compose后没完全启动halo导致异常，现在正常没问题了

**Comment by mjsoftking** [comment]
处理一下也行
![image](https://github.com/nineya/halo-theme-dream2.0/assets/23021469/3b1ba9e4-c327-4dce-82b0-5ec595e66dae)
